openapi: 3.0.3
info:
  version: '1.0'
  title: Fast Food Tech Challenge - Sistema de Gestão
  description: 'API para o sistema de autoatendimento de uma rede de fast food.

    Este projeto gerencia clientes, produtos, pedidos e pagamentos, seguindo as melhores
    práticas de arquitetura de software.

    '
  termsOfService: ''
  license:
    url: https://opensource.org/licenses/MIT
    name: MIT License
servers:
  - url: http://localhost:8080
    description: Localhost
paths:
  /customers:
    get:
      tags:
        - Customer
      summary: Buscar cliente por CPF
      description: 'Localiza e retorna os dados de um cliente específico com base
        no CPF fornecido.

        O CPF deve ser informado como um parâmetro de consulta (query parameter) e
        conter apenas os 11 dígitos.'
      operationId: findCustomer
      parameters:
        - $ref: '#/components/parameters/CpfParam'
      responses:
        '200':
          $ref: '#/components/responses/CustomerResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          description: Cliente não encontrado para o CPF informado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: 404
                message: Not Found
                error:
                  - Customer with document 11122233344 not found
        '500':
          $ref: '#/components/responses/ErrorResponse'
      servers:
        - url: http://localhost:8080
          description: Localhost
      security: &id001
        - bearerAuth: []
    post:
      tags:
        - Customer
      summary: Criar um novo cliente
      description: 'Registra um novo cliente no sistema.

        O CPF é usado como um identificador único. Se um cliente com o mesmo CPF já
        existir, a API retornará um erro de conflito.'
      operationId: createCustomer
      requestBody:
        $ref: '#/components/requestBodies/CustomerRequest'
      responses:
        '201':
          $ref: '#/components/responses/CustomerResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          description: Cliente já cadastrado com o CPF informado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: 409
                message: Conflict
                error:
                  - Customer with document 53731833697 already exists
        '500':
          $ref: '#/components/responses/ErrorResponse'
      servers:
        - url: http://localhost:8080
          description: Localhost
tags:
  - name: Customer
    description: Operações relacionadas a clientes
components:
  parameters:
    CpfParam:
      name: cpf
      in: query
      description: CPF do cliente no formato apenas números
      schema:
        type: string
        pattern: ^\d{11}$
  requestBodies:
    CustomerRequest:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              cpf:
                type: string
                pattern: ^\d{11}$
                minLength: 11
                maxLength: 11
                example: '53731833697'
              name:
                type: string
                minLength: 3
                maxLength: 255
                example: João Cardoso
              email:
                type: string
                format: email
                pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
                maxLength: 255
                example: joao.cardoso@email.com
              phone:
                type: string
                pattern: ^(?:[1-9]{2})(?:[9]{1})?(?:[0-9]{8})$
                minLength: 10
                maxLength: 111
                example: '1134567890'
            required:
              - cpf
              - name
              - email
  responses:
    CustomerResponse:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              email:
                type: string
              cpf:
                type: string
              phone:
                type: string
          examples:
            Example 1:
              value:
                id: 77a73531-d3ab-443e-b46a-6ff7ee5d5d29
                name: Chaves
                email: chaves@email.com
                cpf: '33400276170'
                phone: ''
    ErrorResponse:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
              error:
                type: array
                items:
                  type: string
  schemas:
    ErrorResponse:
      type: object
      title: ErrorResponse
      description: Response de erro
      properties:
        status:
          type: integer
        message:
          type: string
        error:
          type: array
          items:
            type: string
      example:
        status: 400
        message: Requisição inválida
        error:
          - Campo obrigatório 'email' não informado
    UUID:
      type: string
      title: UUID
      description: Identificador único universal no formato UUID.
      format: uuid
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
      example: 241fae7b-0210-4d29-a928-90653c9a9a89